FROM astral/uv:python3.13-alpine

RUN apk update && apk add g++ libc-dev

ENV UV_LINK_MODE=copy

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --group dev

COPY . /app

ENV PYTHONPATH="/app"

ENTRYPOINT []

CMD ["uv", "run", "watchmedo", "auto-restart", "--patterns=*.py", "--debounce-interval", "2", "--recursive", "--", "python", "-u", "src/main.py"]
